name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "node scripts/ensure-sqlite.mjs && npx prisma generate"
dev = "node scripts/ensure-sqlite.mjs && npx prisma migrate deploy && npm exec react-router dev"
